### ISSUE TITLE
Bluetooth devices going Unavailable in HA 2023.10.2 after random period of time.  Requires HA restart to recover.

### ISSUE THREAD

**Issue by ratsputin** [PostLogical/ooler#22]
### System Health details

Not available on Home Assistant Core.

Running 2023.10.2

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Bluetooth connections to Ooler(s) going Unavailable at random.

See issue opened on Bluetooth component: https://github.com/home-assistant/core/issues/102188

This seems to be a side-effect of being forced to migrate to Python 3.11 as of 2023.09, I believe.  It was stable prior to the upgrade.

If you'll check the notes, the author of the Bluetooth integration said the following:

_This very much looks like the library is reusing the connection after its dropped and doesn't try to reconnect._

### Reproduction steps

1. ESPHome Bluetooth proxy loaded on ESP32-PICO
2. Configured two Oolers with ooler custom component
3. Wait for Oolers to go unavailable.  This can take days or minutes after restarting Home Assistant.
...
Note, reloading the component does not fix the issue.  It is necessary to restart Home Assistant.

### Debug logs

```text
Home Assistant logs when devices go unavailable:

Oct 17 16:25:38 ha hass[316282]: Traceback (most recent call last):
Oct 17 16:25:38 ha hass[316282]:   File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 995, in _read_ready__data_received
Oct 17 16:25:38 ha hass[316282]:     data = self._sock.recv(self.max_size)
Oct 17 16:25:38 ha hass[316282]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 17 16:25:38 ha hass[316282]: ConnectionResetError: [Errno 104] Connection reset by peer
Oct 17 16:25:38 ha hass[316282]: The above exception was the direct cause of the following exception:
Oct 17 16:25:38 ha hass[316282]: Traceback (most recent call last):
Oct 17 16:25:38 ha hass[316282]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/homeassistant/components/esphome/bluetooth/client.py", line 100, in _async_wrap_bluetooth_operation
Oct 17 16:25:38 ha hass[316282]:     return await func(self, *args, **kwargs)
Oct 17 16:25:38 ha hass[316282]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 17 16:25:38 ha hass[316282]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/homeassistant/components/esphome/bluetooth/client.py", line 645, in write_gatt_char
Oct 17 16:25:38 ha hass[316282]:     await self._client.bluetooth_gatt_write(
Oct 17 16:25:38 ha hass[316282]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/aioesphomeapi/client.py", line 882, in bluetooth_gatt_write
Oct 17 16:25:38 ha hass[316282]:     await self._send_bluetooth_message_await_response(
Oct 17 16:25:38 ha hass[316282]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/aioesphomeapi/client.py", line 505, in _send_bluetooth_message_await_response
Oct 17 16:25:38 ha hass[316282]:     resp = await self._connection.send_message_await_response_complex(
Oct 17 16:25:38 ha hass[316282]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 17 16:25:38 ha hass[316282]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/aioesphomeapi/connection.py", line 670, in send_message_await_response_complex
Oct 17 16:25:38 ha hass[316282]:     await fut
Oct 17 16:25:38 ha hass[316282]: aioesphomeapi.core.ReadFailedAPIError: Read failed
Oct 17 16:25:38 ha hass[316282]: The above exception was the direct cause of the following exception:
Oct 17 16:25:38 ha hass[316282]: Traceback (most recent call last):
Oct 17 16:25:38 ha hass[316282]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/homeassistant/components/websocket_api/commands.py", line 226, in handle_call_service
Oct 17 16:25:38 ha hass[316282]:     await hass.services.async_call(
Oct 17 16:25:38 ha hass[316282]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/homeassistant/core.py", line 2012, in async_call
Oct 17 16:25:38 ha hass[316282]:     response_data = await coro
Oct 17 16:25:38 ha hass[316282]:                     ^^^^^^^^^^
Oct 17 16:25:38 ha hass[316282]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/homeassistant/core.py", line 2049, in _execute_service
Oct 17 16:25:38 ha hass[316282]:     return await target(service_call)
Oct 17 16:25:38 ha hass[316282]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 17 16:25:38 ha hass[316282]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/homeassistant/helpers/entity_component.py", line 235, in handle_service
Oct 17 16:25:38 ha hass[316282]:     return await service.entity_service_call(
Oct 17 16:25:38 ha hass[316282]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 17 16:25:38 ha hass[316282]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/homeassistant/helpers/service.py", line 876, in entity_service_call
Oct 17 16:25:38 ha hass[316282]:     response_data = await _handle_entity_call(
Oct 17 16:25:38 ha hass[316282]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 17 16:25:38 ha hass[316282]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/homeassistant/helpers/service.py", line 948, in _handle_entity_call
Oct 17 16:25:38 ha hass[316282]:     result = await task
Oct 17 16:25:38 ha hass[316282]:              ^^^^^^^^^^
Oct 17 16:25:38 ha hass[316282]:   File "/srv/homeassistant/.homeassistant/custom_components/ooler/climate.py", line 195, in async_set_hvac_mode
Oct 17 16:25:38 ha hass[316282]:     await client.set_power(power)
Oct 17 16:25:38 ha hass[316282]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/ooler_ble_client/client.py", line 221, in set_power
Oct 17 16:25:38 ha hass[316282]:     await client.write_gatt_char(POWER_CHAR, power_byte, True)
Oct 17 16:25:38 ha hass[316282]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/bleak/__init__.py", line 776, in write_gatt_char
Oct 17 16:25:38 ha hass[316282]:     await self._backend.write_gatt_char(characteristic, data, response)
Oct 17 16:25:38 ha hass[316282]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/homeassistant/components/esphome/bluetooth/client.py", line 86, in _async_wrap_bluetooth_connected_operation
Oct 17 16:25:38 ha hass[316282]:     return await func(self, *args, **kwargs)
Oct 17 16:25:38 ha hass[316282]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 17 16:25:38 ha hass[316282]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/homeassistant/components/esphome/bluetooth/client.py", line 124, in _async_wrap_bluetooth_operation
Oct 17 16:25:38 ha hass[316282]:     raise BleakError(str(err)) from err
Oct 17 16:25:38 ha hass[316282]: bleak.exc.BleakError: Read failed
Oct 17 16:25:38 ha hass[316282]: 2023-10-17 16:25:38.428 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139623976899904] Authenticated connection not ready yet for atom-bluetooth-proxy-acef1c @ 192.168.1.133; current state is ConnectionState.SOCKET_OPENED!
Oct 17 16:25:38 ha hass[316282]: Traceback (most recent call last):
Oct 17 16:25:38 ha hass[316282]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/homeassistant/components/esphome/bluetooth/client.py", line 100, in _async_wrap_bluetooth_operation
Oct 17 16:25:38 ha hass[316282]:     return await func(self, *args, **kwargs)
Oct 17 16:25:38 ha hass[316282]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 17 16:25:38 ha hass[316282]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/homeassistant/components/esphome/bluetooth/client.py", line 645, in write_gatt_char
Oct 17 16:25:38 ha hass[316282]:     await self._client.bluetooth_gatt_write(
Oct 17 16:25:38 ha hass[316282]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/aioesphomeapi/client.py", line 882, in bluetooth_gatt_write
Oct 17 16:25:38 ha hass[316282]:     await self._send_bluetooth_message_await_response(
Oct 17 16:25:38 ha hass[316282]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/aioesphomeapi/client.py", line 500, in _send_bluetooth_message_await_response
Oct 17 16:25:38 ha hass[316282]:     self._check_authenticated()
Oct 17 16:25:38 ha hass[316282]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/aioesphomeapi/client.py", line 351, in _check_authenticated
Oct 17 16:25:38 ha hass[316282]:     raise APIConnectionError(
Oct 17 16:25:38 ha hass[316282]: aioesphomeapi.core.APIConnectionError: Authenticated connection not ready yet for atom-bluetooth-proxy-acef1c @ 192.168.1.133; current state is ConnectionState.SOCKET_OPENED!
Oct 17 16:25:38 ha hass[316282]: The above exception was the direct cause of the following exception:
Oct 17 16:25:38 ha hass[316282]: Traceback (most recent call last):
Oct 17 16:25:38 ha hass[316282]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/homeassistant/components/websocket_api/commands.py", line 226, in handle_call_service
Oct 17 16:25:38 ha hass[316282]:     await hass.services.async_call(
Oct 17 16:25:38 ha hass[316282]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/homeassistant/core.py", line 2012, in async_call
Oct 17 16:25:38 ha hass[316282]:     response_data = await coro
Oct 17 16:25:38 ha hass[316282]:                     ^^^^^^^^^^
Oct 17 16:25:38 ha hass[316282]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/homeassistant/core.py", line 2049, in _execute_service
Oct 17 16:25:38 ha hass[316282]:     return await target(service_call)
Oct 17 16:25:38 ha hass[316282]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 17 16:25:38 ha hass[316282]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/homeassistant/helpers/entity_component.py", line 235, in handle_service
Oct 17 16:25:38 ha hass[316282]:     return await service.entity_service_call(
Oct 17 16:25:38 ha hass[316282]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 17 16:25:38 ha hass[316282]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/homeassistant/helpers/service.py", line 876, in entity_service_call
Oct 17 16:25:38 ha hass[316282]:     response_data = await _handle_entity_call(
Oct 17 16:25:38 ha hass[316282]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 17 16:25:38 ha hass[316282]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/homeassistant/helpers/service.py", line 948, in _handle_entity_call
Oct 17 16:25:38 ha hass[316282]:     result = await task
Oct 17 16:25:38 ha hass[316282]:              ^^^^^^^^^^
Oct 17 16:25:38 ha hass[316282]:   File "/srv/homeassistant/.homeassistant/custom_components/ooler/climate.py", line 195, in async_set_hvac_mode
Oct 17 16:25:38 ha hass[316282]:     await client.set_power(power)
Oct 17 16:25:38 ha hass[316282]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/ooler_ble_client/client.py", line 221, in set_power
Oct 17 16:25:38 ha hass[316282]:     await client.write_gatt_char(POWER_CHAR, power_byte, True)
Oct 17 16:25:38 ha hass[316282]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/bleak/__init__.py", line 776, in write_gatt_char
Oct 17 16:25:38 ha hass[316282]:     await self._backend.write_gatt_char(characteristic, data, response)
Oct 17 16:25:38 ha hass[316282]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/homeassistant/components/esphome/bluetooth/client.py", line 86, in _async_wrap_bluetooth_connected_operation
Oct 17 16:25:38 ha hass[316282]:     return await func(self, *args, **kwargs)
Oct 17 16:25:38 ha hass[316282]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 17 16:25:38 ha hass[316282]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/homeassistant/components/esphome/bluetooth/client.py", line 124, in _async_wrap_bluetooth_operation
Oct 17 16:25:38 ha hass[316282]:     raise BleakError(str(err)) from err
Oct 17 16:25:38 ha hass[316282]: bleak.exc.BleakError: Authenticated connection not ready yet for atom-bluetooth-proxy-acef1c @ 192.168.1.133; current state is ConnectionState.SOCKET_OPENED!
Oct 17 16:26:38 ha hass[316282]: 2023-10-17 16:26:38.476 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139623976899904] Bluetooth GATT Error address=8C:F6:81:F3:AD:4E handle=25 error=-1 description=Not connected
Oct 17 16:26:38 ha hass[316282]: Traceback (most recent call last):
Oct 17 16:26:38 ha hass[316282]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/homeassistant/components/esphome/bluetooth/client.py", line 100, in _async_wrap_bluetooth_operation
Oct 17 16:26:38 ha hass[316282]:     return await func(self, *args, **kwargs)
Oct 17 16:26:38 ha hass[316282]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 17 16:26:38 ha hass[316282]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/homeassistant/components/esphome/bluetooth/client.py", line 645, in write_gatt_char
Oct 17 16:26:38 ha hass[316282]:     await self._client.bluetooth_gatt_write(
Oct 17 16:26:38 ha hass[316282]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/aioesphomeapi/client.py", line 882, in bluetooth_gatt_write
Oct 17 16:26:38 ha hass[316282]:     await self._send_bluetooth_message_await_response(
Oct 17 16:26:38 ha hass[316282]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/aioesphomeapi/client.py", line 510, in _send_bluetooth_message_await_response
Oct 17 16:26:38 ha hass[316282]:     raise BluetoothGATTAPIError(BluetoothGATTError.from_pb(resp[0]))
Oct 17 16:26:38 ha hass[316282]: aioesphomeapi.core.BluetoothGATTAPIError: Bluetooth GATT Error address=8C:F6:81:F3:AD:4E handle=25 error=-1 description=Not connected
Oct 17 16:26:38 ha hass[316282]: The above exception was the direct cause of the following exception:
Oct 17 16:26:38 ha hass[316282]: Traceback (most recent call last):
Oct 17 16:26:38 ha hass[316282]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/homeassistant/components/websocket_api/commands.py", line 226, in handle_call_service
Oct 17 16:26:38 ha hass[316282]:     await hass.services.async_call(
Oct 17 16:26:38 ha hass[316282]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/homeassistant/core.py", line 2012, in async_call
Oct 17 16:26:38 ha hass[316282]:     response_data = await coro
Oct 17 16:26:38 ha hass[316282]:                     ^^^^^^^^^^
Oct 17 16:26:38 ha hass[316282]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/homeassistant/core.py", line 2049, in _execute_service
Oct 17 16:26:38 ha hass[316282]:     return await target(service_call)
Oct 17 16:26:38 ha hass[316282]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 17 16:26:38 ha hass[316282]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/homeassistant/helpers/entity_component.py", line 235, in handle_service
Oct 17 16:26:38 ha hass[316282]:     return await service.entity_service_call(
Oct 17 16:26:38 ha hass[316282]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 17 16:26:38 ha hass[316282]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/homeassistant/helpers/service.py", line 876, in entity_service_call
Oct 17 16:26:38 ha hass[316282]:     response_data = await _handle_entity_call(
Oct 17 16:26:38 ha hass[316282]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 17 16:26:38 ha hass[316282]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/homeassistant/helpers/service.py", line 948, in _handle_entity_call
Oct 17 16:26:38 ha hass[316282]:     result = await task
Oct 17 16:26:38 ha hass[316282]:              ^^^^^^^^^^
Oct 17 16:26:38 ha hass[316282]:   File "/srv/homeassistant/.homeassistant/custom_components/ooler/climate.py", line 195, in async_set_hvac_mode
Oct 17 16:26:38 ha hass[316282]:     await client.set_power(power)
Oct 17 16:26:38 ha hass[316282]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/ooler_ble_client/client.py", line 221, in set_power
Oct 17 16:26:38 ha hass[316282]:     await client.write_gatt_char(POWER_CHAR, power_byte, True)
Oct 17 16:26:38 ha hass[316282]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/bleak/__init__.py", line 776, in write_gatt_char
Oct 17 16:26:38 ha hass[316282]:     await self._backend.write_gatt_char(characteristic, data, response)
Oct 17 16:26:38 ha hass[316282]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/homeassistant/components/esphome/bluetooth/client.py", line 86, in _async_wrap_bluetooth_connected_operation
Oct 17 16:26:38 ha hass[316282]:     return await func(self, *args, **kwargs)
Oct 17 16:26:38 ha hass[316282]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 17 16:26:38 ha hass[316282]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/homeassistant/components/esphome/bluetooth/client.py", line 122, in _async_wrap_bluetooth_operation
Oct 17 16:26:38 ha hass[316282]:     raise BleakError(str(ex)) from ex
Oct 17 16:26:38 ha hass[316282]: bleak.exc.BleakError: Bluetooth GATT Error address=8C:F6:81:F3:AD:4E handle=25 error=-1 description=Not connected

ESPHome logs when device goes unavailable (note, these were captured later, but for the same issue):

[15:06:07][D][esp32_ble_tracker:246]: Starting scan...
[15:11:07][D][esp32_ble_tracker:246]: Starting scan...
[15:16:07][D][esp32_ble_tracker:246]: Starting scan...
[15:21:07][D][esp32_ble_tracker:246]: Starting scan...
[15:26:07][D][esp32_ble_tracker:246]: Starting scan...
[15:31:07][D][esp32_ble_tracker:246]: Starting scan...
[15:36:07][D][esp32_ble_tracker:246]: Starting scan...
[15:41:07][D][esp32_ble_tracker:246]: Starting scan...
[15:46:07][D][esp32_ble_tracker:246]: Starting scan...
[15:51:07][D][esp32_ble_tracker:246]: Starting scan...
[15:56:07][D][esp32_ble_tracker:246]: Starting scan...
[16:01:07][D][esp32_ble_tracker:246]: Starting scan...
[16:06:07][D][esp32_ble_tracker:246]: Starting scan...
[16:11:07][D][esp32_ble_tracker:246]: Starting scan...
[16:15:44][D][api.connection:180]: Home Assistant 2023.10.2 (192.168.1.15) requested disconnected
[16:16:05][D][api:102]: Accepted 192.168.1.15
[16:16:05][W][component:214]: Component api took a long time for an operation (0.05 s).
[16:16:05][W][component:215]: Components should block for at most 20-30ms.
[16:16:05][D][api.connection:1050]: Home Assistant 2023.10.2 (192.168.1.15): Connected successfully
[16:16:07][D][esp32_ble_tracker:246]: Starting scan...
[16:16:09][I][bluetooth_proxy:282]: [0] [8C:F6:81:F3:AD:4E] Connecting v3 without cache
[16:16:09][D][esp32_ble_tracker:214]: Pausing scan to make connection...
[16:16:09][I][esp32_ble_client:064]: [0] [8C:F6:81:F3:AD:4E] 0x00 Attempting BLE connection
[16:16:10][I][esp32_ble_client:196]: [0] [8C:F6:81:F3:AD:4E] Connected
[16:16:10][D][esp32_ble_tracker:246]: Starting scan...
[16:16:12][I][bluetooth_proxy:282]: [1] [0C:43:14:30:C1:5B] Connecting v3 without cache
[16:16:12][D][esp32_ble_tracker:214]: Pausing scan to make connection...
[16:16:12][I][esp32_ble_client:064]: [1] [0C:43:14:30:C1:5B] 0x00 Attempting BLE connection
[16:16:12][I][esp32_ble_client:196]: [1] [0C:43:14:30:C1:5B] Connected
[16:16:12][D][esp32_ble_tracker:246]: Starting scan...
[16:17:48][W][bluetooth_proxy:367]: Cannot write GATT characteristic, not connected
```

### Diagnostics dump

![image](https://github.com/PostLogical/ooler/assets/32401888/456fafa7-6fc0-4580-816c-f22df0f51cab)

**Comment by ratsputin** [comment]
I've looked at your code and it's unclear to me as to why it's not properly handling the disconnect from the Ooler.  I've turned on debugging for the custom component and will report back once I have more information.

**Comment by ratsputin** [comment]
Okay, I received some more information on the issue, although the final error message doesn't make a lot of sense to me:

```
Nov 23 18:42:55 ha hass[784017]: 2023-11-23 18:42:55.887 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Nov 23 18:42:55 ha hass[784017]: Traceback (most recent call last):
Nov 23 18:42:55 ha hass[784017]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/bleak_retry_connector/__init__.py", line 350, in establish_connection
Nov 23 18:42:55 ha hass[784017]:     await client.connect(
Nov 23 18:42:55 ha hass[784017]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/homeassistant/components/bluetooth/wrappers.py", line 292, in connect
Nov 23 18:42:55 ha hass[784017]:     connected = await super().connect(**kwargs)
Nov 23 18:42:55 ha hass[784017]:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 23 18:42:55 ha hass[784017]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/bleak/__init__.py", line 605, in connect
Nov 23 18:42:55 ha hass[784017]:     return await self._backend.connect(**kwargs)
Nov 23 18:42:55 ha hass[784017]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 23 18:42:55 ha hass[784017]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/homeassistant/components/esphome/bluetooth/client.py", line 100, in _async_wrap_bluetooth_operation
Nov 23 18:42:55 ha hass[784017]:     return await func(self, *args, **kwargs)
Nov 23 18:42:55 ha hass[784017]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 23 18:42:55 ha hass[784017]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/homeassistant/components/esphome/bluetooth/client.py", line 367, in connect
Nov 23 18:42:55 ha hass[784017]:     await connected_future
Nov 23 18:42:55 ha hass[784017]: bleak.exc.BleakError: Error ESP_GATT_CONN_FAIL_ESTABLISH while connecting: Connection failed to establish
Nov 23 18:42:55 ha hass[784017]: The above exception was the direct cause of the following exception:
Nov 23 18:42:55 ha hass[784017]: Traceback (most recent call last):
Nov 23 18:42:55 ha hass[784017]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/ooler_ble_client/client.py", line 82, in connect
Nov 23 18:42:55 ha hass[784017]:     await self._ensure_connected()
Nov 23 18:42:55 ha hass[784017]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/ooler_ble_client/client.py", line 126, in _ensure_connected
Nov 23 18:42:55 ha hass[784017]:     client = await establish_connection(
Nov 23 18:42:55 ha hass[784017]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 23 18:42:55 ha hass[784017]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/bleak_retry_connector/__init__.py", line 438, in establish_connection
Nov 23 18:42:55 ha hass[784017]:     _raise_if_needed(name, device.address, exc)
Nov 23 18:42:55 ha hass[784017]:   File "/srv/homeassistant/venv/lib/python3.11/site-packages/bleak_retry_connector/__init__.py", line 323, in _raise_if_needed
Nov 23 18:42:55 ha hass[784017]:     raise BleakAbortedError(f"{msg}: {ABORT_ADVICE}") from exc
Nov 23 18:42:55 ha hass[784017]: bleak_retry_connector.BleakAbortedError: OOLER-92111190173 - 8C:F6:81:F3:AD:4E: Failed to connect after 9 attempt(s): Error ESP_GATT_CONN_FAIL_ESTABLISH while connecting: Connection failed to establish: Interference/range; External Bluetooth adapter w/extension may help; Extension cables reduce USB 3 port interference
```
As I'm using an ATOM-Lite for my Bluetooth proxy, there's no external Bluetooth adapter.

I'm assuming this situation would be caused by the Ooler not responding in a timely manner (this happened with the other Ooler 29 minutes later).  When this sort of situation occurs, the only way to resolve the issue is to restart Home Assistant.  Even reloading the Ooler add-on doesn't do it, nor does restarting the ATOM.

As far as I know, there are no interference sources near my Oolers, so I'm unclear as to why they'd just stop responding.

**Comment by ratsputin** [comment]
Is it possible the Oolers were being upgraded OTA and went offline long enough for the Bluetooth connection attempts to timeout?

**Comment by PostLogical** [comment]
So I'm not sure of this yet, but I'm guessing that I run into the same issue myself at times. I think it might have to do with having too many devices connecting to the same bluetooth proxy. These are active connections, and there is a documented limit to the number of active connections in this esphome component. I've typically been able to just click the Bluetooth Connection toggle and get the connection back on both my Oolers, but sometimes it seems more complicated than that which might have to do with my trying to connect one or two other bluetooth devices to this proxy. It's been over a year since you wrote in, so please do say if this is still a problem I should investigate. Thanks!

**Comment by Tesla808019** [comment]
Confirming I am also seeing this on the latest Home Assistant. Doesnt stay connected to bluetooth for long at all.

**Comment by PostLogical** [comment]
This should be fixed in the newest pre-release/dev branch, but I'll leave this open until I (and anyone else who is willing) tests out the latest pre-release for a while.

**Comment by chrisg30** [comment]
Ooler was unavailable, updated to 2026.3.2b3, restarted HA. Ooler was still unavailable. Had to re-pair to bring it back online which it is now. Usually it drops off after half an hour or so although I've seen several days uptime on the previous 2024.12.1 version. Will monitor...

**Comment by PostLogical** [comment]
Thanks so much for testing this! I really thought I was just alerting people that I've been working on a fix, but it's much more exciting to see someone jump on the beta!

I've done some more work on this today and hopefully it fixes your issues and makes it so you don't notice any unintentional disconnects in the future. I have a guess that the number of notifications could have been contributing to instability because esp-idf can only handle 9 total notification channels at a time and esphome can handle 12. If you have something running with esp-idf (or any bluetooth that can't handle the 12 that my proxy is running at) then that could contribute to why you were getting such worse results than I was. It may have also been the changes to reconnection playing out differently in our environments. Hopefully the newest pre-release fixes that. If you run into trouble with it, please add the code below to your configuration.yaml and reboot to get debug logs that you could submit for me to take a look at. Thanks!

logger:
  default: warning
  logs:
    custom_components.ooler: debug
    ooler_ble_client: debug

**Comment by chrisg30** [comment]
Thank you for creating it! 

Last night, I ran with just the bluetooth I have attached to my HA server but it wasn't quite up to the job - the signal is borderline. 
But... instead of becoming and staying unavailable, Ooler was coming back online repeatedly. 
Another thing I noticed, that wasn't happening before, was consuming an active slot/connection on the HA bluetooth stack.

Tonight, I'm trying it again but I've got a Shelly Blu Gateway nearby to help and I can see the connection is being routed through it. Hopefully it'll be solid now but it's looking so much better with the changes you made.

Thanks again!

**Comment by PostLogical** [comment]
> Shelly Blu Gateway

Nice. Let me know how that works. And make sure you're using the latest pre-release as it has all the changes. https://github.com/PostLogical/ooler/releases/tag/2026.3.3b2

**Comment by PostLogical** [comment]
Try out the new official release, which should hopefully take care of all concerns here and some more while adding sleep schedule functionality. Let me know here if you have any issues. If I don't here back in a couple weeks I'll probably close the issue, but you could always reopen if the issue persists.

**Comment by chrisg30** [comment]
Yes, it's been solid since rc3 I think it was. I just upgraded to the official release. All good here. Thanks for your excellent work :)

**Comment by PostLogical** [comment]
Awesome to hear; thanks so much! I'll wait a couple weeks to close this in case anything surfaces, but given the results in my house, I'm pretty optimistic.

**Comment by PostLogical** [comment]
I'm going to consider this taken care of as there have been no reports of continued issues after the overhaul.
